"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
type M={id:number;date:string;type:"Entrada"|"Saída"|"Ajuste";qty:number;doc:string;vehicle:string;owner:string;reason?:string;adjustmentDelta?:number|null;scheduledLoadId?:number|null};
type ScheduledLoad={id:number;date:string;qty:number;doc:string;vehicle:string;status:string;owner:string};
export default function Home(){
 const [session,setSession]=useState<any>(null),[items,setItems]=useState<M[]>([]),[users,setUsers]=useState<any[]>([]),[loads,setLoads]=useState<ScheduledLoad[]>([]),[logs,setLogs]=useState<any[]>([]),[tab,setTab]=useState("dashboard"),[notice,setNotice]=useState(""),[pendingEntry,setPendingEntry]=useState<ScheduledLoad|null>(null),[movementType,setMovementType]=useState<M["type"]>("Entrada");
 const load=async()=>{const [m,s]=await Promise.all([fetch("/api/movements"),fetch("/api/scheduled")]);if(m.ok)setItems((await m.json()).map((x:any)=>({...x,qty:x.qty/1000,adjustmentDelta:x.adjustmentDelta===null?null:x.adjustmentDelta/1000})));if(s.ok)setLoads((await s.json()).map((x:any)=>({...x,qty:x.qty/1000})))};
 useEffect(()=>{fetch("/api/session").then(async r=>({status:r.status,...await r.json()})).then(x=>{setSession(x);if(x.authorized)load()})},[]);
 const stock=useMemo(()=>items.reduce((s,x)=>s+movementEffect(x),0),[items]),freeSpace=Math.max(0,120-stock),entries=items.filter(x=>x.type==="Entrada").reduce((s,x)=>s+x.qty,0),exits=items.filter(x=>x.type==="Saída").reduce((s,x)=>s+x.qty,0);
 const tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1);const tomorrowKey=localDateKey(tomorrow),activeD1Loads=loads.filter(x=>(x.status==="Programada"||x.status==="Em trânsito")&&x.date<=tomorrowKey),projectedD1=stock+activeD1Loads.reduce((s,x)=>s+x.qty,0),projectedFreeSpace=120-projectedD1,occupancy=Math.min(100,Math.max(0,stock/120*100)),pendingReceived=loads.filter(x=>x.status==="Recebida"&&!items.some(item=>item.scheduledLoadId===x.id));
 const recentExits=items.filter(x=>x.type==="Saída"&&new Date(x.date)>=new Date(Date.now()-30*86400000));const daily=recentExits.reduce((s,x)=>s+x.qty,0)/30;const autonomy=daily>0?stock/daily:null;
 if(!session)return <Access title="Validando acesso…" text="Aguarde enquanto sua sessão é confirmada."/>;if(session.status===401)return <Access title={session.setup?"Primeiro acesso":"Entre para continuar"} text={session.setup?"Crie a conta administradora inicial do GER.":"Use seu e-mail e senha para acessar o GER."} login setup={!!session.setup}/>;if(!session.authorized)return <Access title="Acesso indisponível" text="Sua sessão não está autorizada."/>;
 const u=session.user,admin=u.role==="admin",first=u.name.split(" ")[0],initials=u.name.split(/\s+/).slice(0,2).map((n:string)=>n[0]).join("").toUpperCase(),mine=items.filter(x=>x.owner==u.name);
 async function movement(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),body={...Object.fromEntries(f),scheduledLoadId:pendingEntry?.id};const r=await fetch("/api/movements",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),d=await r.json();setNotice(r.ok?"Movimentação registrada com sucesso.":d.error);if(r.ok){e.currentTarget.reset();setPendingEntry(null);setMovementType("Entrada");await load()}}
 async function schedule(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),r=await fetch("/api/scheduled",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(f))});setNotice(r.ok?"Carga programada com sucesso.":"Não foi possível programar a carga.");if(r.ok){e.currentTarget.reset();await load()}}
 async function openUsers(){setTab("users");const r=await fetch("/api/users");if(r.ok)setUsers(await r.json())}async function openAudit(){setTab("audit");const r=await fetch("/api/audits");if(r.ok)setLogs(await r.json())}
 async function setUserActive(id:number,active:boolean){const r=await fetch("/api/users",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,active})});const d=await r.json().catch(()=>({}));setNotice(r.ok?(active?"Usuário reativado com sucesso.":"Usuário bloqueado com sucesso."):(d.error||"Não foi possível alterar o usuário."));if(r.ok)openUsers()}
 async function addUser(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),r=await fetch("/api/users",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(f))}),d=await r.json();setNotice(r.ok?"Usuário criado com sucesso.":d.error);if(r.ok){e.currentTarget.reset();openUsers()}}
 async function setLoad(loadItem:ScheduledLoad,status:string){const r=await fetch("/api/scheduled",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:loadItem.id,status})});const d=await r.json().catch(()=>({}));if(!r.ok){setNotice(d.error||"Não foi possível alterar a programação.");return}await load();if(status==="Recebida"){setPendingEntry({...loadItem,status});setNotice("Programação recebida. Confira os dados e confirme a entrada no estoque.");setTab("new")}}
 function resumeEntry(loadItem:ScheduledLoad){setPendingEntry(loadItem);setNotice("Entrada recebida aguardando confirmação. Confira os dados antes de registrar.");setTab("new")}
 async function deleteMovement(item:M){if(!confirm(`Excluir o lançamento ${item.type} de ${item.qty.toFixed(2)} t, documento ${item.doc}?\n\nEsta ação ficará registrada na auditoria.`))return;const r=await fetch("/api/movements",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id:item.id})}),d=await r.json().catch(()=>({}));setNotice(r.ok?"Lançamento excluído com sucesso.":d.error||"Não foi possível excluir o lançamento.");if(r.ok)await load()}
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});location.reload()}
 const status=stock<12?"Crítico":stock<=24?"Atenção":"Normal";
 return <main><header className="topbar"><div className="brand"><strong>GER</strong><span>Gestão de Estoque e Registros</span></div><h1>{new Date().getHours()<12?"Bom dia":new Date().getHours()<18?"Boa tarde":"Boa noite"}, <em>{first}</em></h1><div className="account"><span className="rolePill">{admin?"Administrador":"Operador"}</span><div className="accountAvatar">{initials}</div></div></header>
 <nav><N t="dashboard" tab={tab} set={setTab} i="▦" l="Dashboard"/><N t="new" tab={tab} set={setTab} i="＋" l="Lançamento"/><N t="history" tab={tab} set={setTab} i="☷" l="Histórico"/><N t="scheduled" tab={tab} set={setTab} i="▣" l="Programação"/><N t="mine" tab={tab} set={setTab} i="◎" l="Minha atividade"/>{admin&&<><button className={tab==="audit"?"active":""} onClick={openAudit}>⌁ <span>Auditoria</span></button><button className={tab==="users"?"active":""} onClick={openUsers}>♙ <span>Usuários</span></button></>}</nav>
 <div className="shell">{tab==="dashboard"&&<><section className="hero"><div className="heroMetrics"><div className="heroMetric"><p>ESTOQUE DISPONÍVEL</p><strong>{stock.toFixed(2)}<small> t</small></strong><span className={`badge ${status==="Normal"?"ok":status==="Atenção"?"warn":"danger"}`}>{status}</span></div><div className="heroMetric freeSpace"><p>ESPAÇO LIVRE</p><strong>{freeSpace.toFixed(2)}<small> t</small></strong><span className="capacityNote">de 120 t de capacidade</span></div></div><div className="siloVisual"><img src="/silo-production.png" alt="Silo industrial de cimento"/><b>Ocupação atual · {occupancy.toFixed(1)}%</b><div className="occupancyTrack"><span style={{width:`${occupancy}%`}}/></div><p>Capacidade total: 120 t</p></div></section>{projectedFreeSpace<0?<section className="operationalAlert danger"><b>⚠ Capacidade projetada excedida em {Math.abs(projectedFreeSpace).toFixed(2)} t até D+1</b><span>Revise as cargas programadas e em trânsito previstas até amanhã.</span></section>:<section className="operationalAlert ok"><b>Espaço livre projetado D+1: {projectedFreeSpace.toFixed(2)} t</b><span>Considera somente cargas ativas previstas até amanhã.</span></section>}{pendingReceived.length>0&&<section className="operationalAlert pending"><div><b>{pendingReceived.length} {pendingReceived.length===1?"entrada recebida aguarda":"entradas recebidas aguardam"} confirmação</b><span>O estoque ainda não foi atualizado.</span></div><button type="button" onClick={()=>resumeEntry(pendingReceived[0])}>Retomar lançamento</button></section>}<section className="scheduleSummary"><StatusSummary status="Programada" count={loads.filter(x=>x.status==="Programada").length}/><StatusSummary status="Em trânsito" count={loads.filter(x=>x.status==="Em trânsito").length}/><StatusSummary status="Recebida" count={pendingReceived.length} label="Aguardando entrada"/><StatusSummary status="Cancelada" count={loads.filter(x=>x.status==="Cancelada").length}/></section><section className="cards four"><Card i="↘" c="green" l="Entradas" v={`${entries.toFixed(2)} t`} s="Acumulado"/><Card i="↗" c="blue" l="Saídas" v={`${exits.toFixed(2)} t`} s="Acumulado"/><Card i="◒" c="orange" l="Autonomia" v={autonomy?`${autonomy.toFixed(1)} dias`:"Sem consumo"} s="Média dos últimos 30 dias"/><Card i="▣" c={projectedFreeSpace<0?"orange":"blue"} l="Estoque projetado D+1" v={`${projectedD1.toFixed(2)} t`} s={`${activeD1Loads.length} carga${activeD1Loads.length===1?"":"s"} ativa${activeD1Loads.length===1?"":"s"} até amanhã`}/></section><Panel title="Histórico recente"><Table items={items.slice(0,5)}/></Panel></>}
 {tab==="new"&&<section className="formPanel"><div className="formIntro"><span>＋</span><p>NOVO LANÇAMENTO</p><h2>Registrar movimentação</h2><small>{pendingEntry?`Entrada originada da programação #${pendingEntry.id}. Confira os dados antes de confirmar.`:movementType==="Ajuste"?"Informe o nível físico correto. O saldo será substituído pelo valor informado.":"O saldo e a auditoria serão atualizados automaticamente."}</small></div><form key={pendingEntry?.id||"manual"} onSubmit={movement}><label>Tipo{pendingEntry?<><input value="Entrada" readOnly/><input type="hidden" name="type" value="Entrada"/></>:<select name="type" value={movementType} onChange={e=>setMovementType(e.target.value as M["type"])} required><option>Entrada</option><option>Saída</option>{admin&&<option>Ajuste</option>}</select>}</label><div className="two"><label>Data<input name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></label><label>{movementType==="Ajuste"&&!pendingEntry?"Nível correto atual (t)":"Quantidade (t)"}<input name="qty" type="number" min="0.01" max={movementType==="Ajuste"?"120":undefined} step="0.01" defaultValue={pendingEntry?.qty} readOnly={!!pendingEntry} required/>{movementType==="Ajuste"&&!pendingEntry&&<small className="fieldHint">O saldo final ficará exatamente neste nível.</small>}</label></div><div className="two"><label>Documento<input name="doc" defaultValue={pendingEntry?.doc} readOnly={!!pendingEntry} required/></label><label>Veículo<input name="vehicle" defaultValue={pendingEntry?.vehicle} readOnly={!!pendingEntry} required/></label></div>{admin&&!pendingEntry&&<label>Justificativa do ajuste<input name="reason" placeholder="Obrigatória somente para ajustes" required={movementType==="Ajuste"}/></label>}<label>Responsável<input value={u.name} readOnly/></label><Msg v={notice}/><button className="primary">{pendingEntry?"Confirmar entrada":movementType==="Ajuste"?"Confirmar novo nível":"Registrar movimentação"}</button></form></section>}
 {tab==="history"&&<><Msg v={notice}/><Panel title="Histórico completo"><Table items={items} onDelete={admin?deleteMovement:undefined}/></Panel></>}
 {tab==="mine"&&<><section className="profileHero"><div className="profileAvatar">{initials}</div><div><p>ÁREA PESSOAL</p><h2>{u.name}</h2><span>{admin?"Administrador":"Operador"}</span></div><div className="personalKpi"><small>Meus lançamentos</small><b>{mine.length}</b></div><div className="personalKpi"><small>Volume movimentado</small><b>{mine.reduce((s,x)=>s+x.qty,0).toFixed(2)} t</b></div></section><Panel title="Lançamentos realizados por mim"><Table items={mine}/></Panel></>}
 {tab==="scheduled"&&<section className="usersGrid"><section className="panel userForm"><div className="panelTitle"><div><p>RECEBIMENTOS</p><h2>Programar carga</h2></div></div><form onSubmit={schedule}><label>Data prevista<input name="date" type="date" required/></label><label>Quantidade (t)<input name="qty" type="number" step="0.01" required/></label><label>Documento<input name="doc" required/></label><label>Veículo<input name="vehicle" required/></label><Msg v={notice}/><button className="primary">Programar carga</button></form></section><Panel title="Cargas previstas"><div className="scheduleSummary compact"><StatusSummary status="Programada" count={loads.filter(x=>x.status==="Programada").length}/><StatusSummary status="Em trânsito" count={loads.filter(x=>x.status==="Em trânsito").length}/><StatusSummary status="Recebida" count={pendingReceived.length} label="Aguardando entrada"/><StatusSummary status="Cancelada" count={loads.filter(x=>x.status==="Cancelada").length}/></div><div className="userList">{loads.map(x=>{const launched=items.some(item=>item.scheduledLoadId===x.id),displayStatus=launched?"Entrada lançada":x.status;return <article key={x.id} className={`loadStatus ${statusClass(displayStatus)}`}><div className="avatar">▣</div><div><b>{x.qty.toFixed(2)} t · {x.vehicle}</b><small>{new Date(x.date+"T12:00").toLocaleDateString("pt-BR")} · {x.doc}</small><span className={`statusPill ${statusClass(displayStatus)}`}>{displayStatus}</span></div><select value={x.status} disabled={launched} onChange={e=>setLoad(x,e.target.value)}><option>Programada</option><option>Em trânsito</option><option>Recebida</option><option>Cancelada</option></select></article>})}</div></Panel></section>}
 {tab==="audit"&&<Panel title="Trilha de auditoria"><div className="tableWrap"><table><thead><tr><th>Data e hora</th><th>Usuário</th><th>Ação</th><th>Registro</th></tr></thead><tbody>{logs.map(x=><tr key={x.id}><td>{new Date(x.createdAt).toLocaleString("pt-BR")}</td><td>{x.userEmail}</td><td>{x.action}</td><td>{x.entity} #{x.entityId}</td></tr>)}</tbody></table></div></Panel>}
 {tab==="users"&&<section className="usersGrid"><section className="panel userForm"><div className="panelTitle"><h2>Criar acesso</h2></div><form onSubmit={addUser}><label>Nome<input name="name" required/></label><label>E-mail<input name="email" type="email" required/></label><label>Senha inicial<input name="password" type="password" minLength={8} required/></label><label>Perfil<select name="role"><option value="operator">Operador</option><option value="admin">Administrador</option></select></label><Msg v={notice}/><button className="primary">Criar usuário</button></form></section><Panel title="Usuários cadastrados"><div className="userList">{users.map(x=><article key={x.id}><div className="avatar">{x.name[0]}</div><div><b>{x.name}</b><small>{x.email} · {x.role} · {x.active?"Ativo":"Bloqueado"}</small></div>{x.id!==u.id&&<button type="button" className={x.active?"block":"enable"} onClick={()=>setUserActive(x.id,!x.active)}>{x.active?"Bloquear":"Reativar"}</button>}</article>)}</div></Panel></section>}</div><footer><span>● {u.name} · {admin?"Administrador":"Operador"}</span><button type="button" className="logoutLink" onClick={logout}>Sair</button></footer></main>}
function Access(p:{title:string;text:string;login?:boolean;setup?:boolean}){
 const [msg,setMsg]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setMsg("");const f=new FormData(e.currentTarget);const body=Object.fromEntries(f);const endpoint=p.setup?"/api/auth/setup":"/api/auth/login";const r=await fetch(endpoint,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok){setMsg(d.error||"Não foi possível acessar.");return}location.reload()}
 return <main className="access"><div className="loginCard"><b>GER · ACESSO PROTEGIDO</b><h1>{p.title}</h1><p>{p.text}</p>{p.login&&<form onSubmit={submit}>{p.setup&&<label>Nome<input name="name" autoComplete="name" required/></label>}<label>E-mail<input name="email" type="email" autoComplete="email" required/></label><label>Senha<input name="password" type="password" minLength={8} autoComplete={p.setup?"new-password":"current-password"} required/></label>{p.setup&&<label>Confirmar senha<input name="confirmPassword" type="password" minLength={8} autoComplete="new-password" required/></label>}{msg&&<p className="loginError">{msg}</p>}<button className="primary" type="submit">{p.setup?"Criar administrador":"Entrar"}</button></form>}</div></main>}
function N(p:any){return <button className={p.tab===p.t?"active":""} onClick={()=>p.set(p.t)}>{p.i} <span>{p.l}</span></button>}function Card(p:any){return <article><span className={`icon ${p.c}`}>{p.i}</span><div><p>{p.l}</p><strong>{p.v}</strong><small>{p.s}</small></div></article>}function Panel(p:any){return <section className="panel"><div className="panelTitle"><div><p>GER</p><h2>{p.title}</h2></div></div>{p.children}</section>}function Msg({v}:{v:string}){return v?<p className={`notice ${v.includes("sucesso")?"success":"error"}`}>{v}</p>:null}function Table({items,onDelete}:{items:M[];onDelete?:(item:M)=>void}){return <div className="tableWrap"><table><thead><tr><th>Data</th><th>Movimentação</th><th>Quantidade</th><th>Documento</th><th>Veículo</th><th>Responsável</th>{onDelete&&<th>Ações</th>}</tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{new Date(x.date+"T12:00").toLocaleDateString("pt-BR")}</td><td><span className={`movement ${x.type.toLowerCase()}`}>{x.type}</span></td><td><b>{x.qty.toFixed(2)} t</b></td><td>{x.doc}</td><td>{x.vehicle}</td><td>{x.owner}</td>{onDelete&&<td><button type="button" className="deleteMovement" onClick={()=>onDelete(x)}>Excluir</button></td>}</tr>)}</tbody></table></div>}
function localDateKey(date:Date){const year=date.getFullYear(),month=String(date.getMonth()+1).padStart(2,"0"),day=String(date.getDate()).padStart(2,"0");return `${year}-${month}-${day}`}function statusClass(status:string){return status.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\s+/g,"-")}function StatusSummary({status,count,label}:{status:string;count:number;label?:string}){return <article className={`statusSummary ${statusClass(status)}`}><span>{count}</span><div><b>{label||status}</b><small>{label?status:"Programações"}</small></div></article>}
function movementEffect(item:M){return item.type==="Saída"?-item.qty:item.type==="Ajuste"&&item.adjustmentDelta!==null&&item.adjustmentDelta!==undefined?item.adjustmentDelta:item.qty}
