import { asc, eq } from "drizzle-orm";
import { getDb } from "../../../db";
import { users } from "../../../db/schema";
import { hashPassword, isAdmin } from "../../auth";
import { getD1 } from "../../d1";

export async function GET(){if(!await isAdmin())return Response.json({error:"Acesso restrito"},{status:403});return Response.json(await getDb().select({id:users.id,name:users.name,email:users.email,role:users.role,active:users.active,createdAt:users.createdAt}).from(users).orderBy(asc(users.role),asc(users.name)))}
export async function POST(req:Request){if(!await isAdmin())return Response.json({error:"Acesso restrito"},{status:403});const b=await req.json() as {name?:string;email?:string;role?:string;password?:string};const name=b.name?.trim(),email=b.email?.trim().toLowerCase(),password=String(b.password??"");const role:"admin"|"operator"=b.role==="admin"?"admin":"operator";if(!name||!email||!/^\S+@\S+\.\S+$/.test(email))return Response.json({error:"Nome e e-mail são obrigatórios."},{status:400});if(password.length<8)return Response.json({error:"A senha deve ter ao menos 8 caracteres."},{status:400});try{await getDb().insert(users).values({name,email,passwordHash:await hashPassword(password),role,active:true,createdAt:new Date().toISOString()})}catch{return Response.json({error:"Este e-mail já está cadastrado."},{status:409})}return Response.json({ok:true},{status:201})}
export async function PATCH(req:Request){const admin=await isAdmin();if(!admin)return Response.json({error:"Acesso restrito"},{status:403});const b=await req.json() as {id?:number;active?:boolean};if(!b.id)return Response.json({error:"Usuário inválido."},{status:400});if(b.id===admin.id&&!b.active)return Response.json({error:"Você não pode bloquear sua própria conta."},{status:400});await getDb().update(users).set({active:!!b.active}).where(eq(users.id,b.id));if(!b.active)await getD1().prepare("DELETE FROM sessions WHERE user_id = ?").bind(b.id).run();return Response.json({ok:true})}
